fix: 修复gradio和fastapi带来的版本问题 (#1167)
* fix: pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class starlette.requests.Request>错误

* fix: ImportError: cannot import name 'lower_char' from 'multipart.multipart'

* Revert "fix: ImportError: cannot import name 'lower_char' from 'multipart.multipart'"

This reverts commit a7e98d44b6c2a6fb045ec32bb431aa31da07ef08.

* fix: ImportError: cannot import name 'lower_char' from 'multipart.multipart'
fix: raise PydanticSchemaGenerationError(pydantic.errors.PydanticSchemaGenerationError

* fix: pydantic.errors.PydanticSchemaGenerationError